### ISSUE TITLE
Disable trailing/beginning gaps

### ISSUE THREAD

**Issue by pdufog** [hammock-dev/hammock#1]
Two issues:
1. The trailing/beginning gaps can't be disabled. For clustering phage peptides, it is sometimes desirable to have no sequence shift in alignment and no gaps. With the options  -x 0 -p -1000, still a lot of gaps were added to either ends. I am wondering if there is a way to disable gaps on either ends. 
2. Can Hammock capture pairwise correlation often seen in motifs, and how, and where in the output? It was mentioned in the introduction of the publication.

**Comment by krejciadam** [comment]
Hi! 

1. The `-x` and ` -p` options are both only relevant for the initial clustering phase (i.e. `greedy` and `clinkage` modes or the first phase of `full` mode). Using `-x 0` is indeed sufficient to force no trailing gaps in the output, but only in the output of the initial phase of clustering: files `initial_clusters.tsv` and `initial_clusters_sequences.tsv`. 
Forcing no trailing gaps in the second phase of clustering (the HMM phase) is not supported. In theory, it could be possible, as both Hmmer and HH-suite have some parameters for gap penalties, as well as for how local/global the behavior of the alignment algorithm is. I believe there is little merit in HMM-based clustering with gaps disabled. In any case, it is always possible to experiment with the parameters of the HMM tools using the `settings/settings.prop` files. You can alter the default parameters of `hmmalign` and `hhsearch` commands there. Refer to Hmmber and HH-suite manuals for full description of their parameters. 

2. There is no explicit representation of correlated positions in Hammock - such phenomena are captured by multiple motifs. A different internal motif representation (like neural networks) would be needed to work directly with correlated positions. For Hammock, some means of post-analysis across sequence clusters would be necessary to discover possible correlations.
