### ISSUE TITLE
unique sequences vs redundant sequences as input of Hammock

### ISSUE THREAD

**Issue by cn6659** [hammock-dev/hammock#10]
In the input fasta,
The total sequences: 6,484
The unique sequences:3,521

1) When using 6,484 total sequences, 58 clusters and 455 unique sequences in the output.
2) When using 3,521 unique sequences, 49 clusters and 466 unique sequences in the output.

Hammock starts with the extraction of unique sequences.
I was wondering
- why 1) and 2) are different clusters and output after the step of extraction of unique sequences in the Hammock.
- the redundant sequences may affect the calculation of the clustering score.

**Comment by krejciadam** [comment]
Hi!
  My best guess is that your two inputs will result in different effective order. Due to the heuristic used, the results do depend on the order in which sequences are processed. By default, sequences are ordered by # of copies with alphabetical order in case of ties. So removing replicated sequences effectively changes the order to alphabetical. 

See ```-R, --order``` parameter for details.

**Comment by cfz1998** [comment]
> Hi! My best guess is that your two inputs will result in different effective order. Due to the heuristic used, the results do depend on the order in which sequences are processed. By default, sequences are ordered by # of copies with alphabetical order in case of ties. So removing replicated sequences effectively changes the order to alphabetical.
> 
> See `-R, --order` parameter for details.

Hi, @krejciadam !
1.What's the means about unique seqs? It's the no-redundancy of total seqs?
2.If it is, could i using cd-hit to get nr_seqs?
3.Should I must using nr_seqs for hammock?

Thats all my problems. 
Thank you for your reply!
-zcf

**Comment by krejciadam** [comment]
Hi!
  I'm having some trouble understanding your questions. 

1: As I wrote, the effective order of input sequences may have an effect on clustering results and the # of times a sequence is exactly repeated in the input has an effect on the effective order by default. See ```-R, --order``` parameter for details.
2: What do you mean by ```nr_seqs``` ? In any case, I don't see any obvious way of using cd-hit to pre-process data for Hammock.
3: see 2:
