### ISSUE TITLE
Greedy clustering. Maybe wrong input file format?

### ISSUE THREAD

**Issue by cfz1998** [hammock-dev/hammock#11]
Hi, Krejciadam!
I got a error!

`
Hammock version 1.2.0 Run with --help for a brief description of command line parameters.

HHLIB env. variable not set. Setting to: /data/chaofan/software/Hammock/hhsuite-2.0.16/lib/hh/
Loading input sequences...
98683 unique sequences loaded.
100697 total sequences loaded.
98683 unique sequences after non-specified labels filtered out
100697 total sequences after non-specified labels fileterd out
Shortest sequence: 1 AA. Longest sequence: 200 AA.
More than 10 000 unique sequences. Using greedy clustering. Use --use_clinkage to force clinkage clustering
Max shift not set. Setting automatically to: 0
Generating input statistics...
Greedy clustering threshold not set. Setting automatically to: 174
Initial greedy clusters limit not set. Setting automatically to: 2467
Greedy clustering...
Error. Maybe wrong input file format? Run with --help for a brief description of command line parameters. Trace:

java.lang.NullPointerException
	at cz.krejciadam.hammock.LimitedGreedySequenceClusterer.firstPhase(LimitedGreedySequenceClusterer.java:104)
	at cz.krejciadam.hammock.LimitedGreedySequenceClusterer.cluster(LimitedGreedySequenceClusterer.java:41)
	at cz.krejciadam.hammock.Hammock.runGreedyClustering(Hammock.java:409)
	at cz.krejciadam.hammock.Hammock.runFull(Hammock.java:376)
	at cz.krejciadam.hammock.Hammock.parseArgs(Hammock.java:271)
	at cz.krejciadam.hammock.Hammock.main(Hammock.java:145)
`
When i used 10k seqs, its works fine! But when i used 100k seqs, its return a error!
I don't know why.

Thank you for your reply!
--zcf

**Comment by cfz1998** [comment]
For more than 10k seqs, I used 
```python
Hammock.jar full --use_clinkage
```
It's don't case this error! But memory is OUT!

**Comment by cfz1998** [comment]
> For more than 10k seqs, I used
> 
> ```python
> Hammock.jar full --use_clinkage
> ```
> 
> It's don't case this error! But memory is OUT!

There are no '|' in fasta_header and "X" in seqs.

**Comment by krejciadam** [comment]
Hi! Can you please share the input file producing the error?
