### ISSUE TITLE
Different initial clustering depending on size of input

### ISSUE THREAD

**Issue by isthisthat** [hammock-dev/hammock#12]
Hello, I was wondering if you could help me understand this conceptually. When I cluster a set of say 30 unique peptides, I get some members clustered together (in groups of 2 or 3). When those 30 are part of a list of say 10000 unique peptides, there are no clusters between them and all 30 appear as singletons. I'm referring to the initial clustering step (not the HMM merging and extension) and I'm using clinkage clustering. I would have thought that the initial clustering step is deterministic (when using clinkage) and that those 30 would always cluster in the same way no matter the context. Why am I seeing this difference? Is it because at the end of initial clustering only the largest clusters as kept as "cores"? So in a larger dataset you would keep a different set than in a smaller dataset? Is there a way to emit all initial clusters, regardless of their fate downstream? I thought that's what the "inital_clusters*.csv" files were supposed to be but apparently not. Thank you for your input!

**Comment by krejciadam** [comment]
Hi!

I'll try to shed some light on this. 

In general, if two sequences A and B from are clustered together by `clinkage` when they are part of a small dataset, it does not mean they will be clustered together if they are part of a larger dataset.
 Imagine this situation: 

- The small dataset comprises 2 sequences A and B
- The large datasets comprises 3 sequences A B and C
- Similarity between A and B is 21. Similarity between A and C is 22, similarity between B and C is 19. 
- Similarity threshold for clinkage clustering is 20. 

In the small dataset, A and B will join to form a single cluster. 
In the large dataset, first, A and C will join to form a cluster. Then the similarity score between B and this cluster is 19 (the minimum of [BC] and [BA] similarities), hence B will not join this cluster and will remain a singleton. 

So `clinkage` clustering is indeed context dependent. This is the result of using alignment scores and complete-linkage criterion. 

Heaving said that, if there was any clustering between your 30 sequences in the smaller dataset, they should not end up being all singletons when part of a larger dataset. At least some of them should be part of some cluster. The obvious reasons for this I could think of are that Hammock by default changes the initial routine from "clinkage" to "greedy" for datasets with 10k+ sequences and also if `-g, --alignment_threshold` is not set, it might end up being automatically set to a different value depending on your dataset. Does this happen when you run in `clinkage` mode with `-g` fixed? 

The initial cluster files (`initial_clusters.tsv, initial_clusters_sequences.tsv, initial_clusters_sequences_original_order.tsv`) contain all the initial clusters, not just the cores selected for the following step.

**Comment by isthisthat** [comment]
Hi Adam, thanks for the response! That makes a lot of sense. I purposely force clinkage to avoid switching to greedy but I think I've been caught out by `-g`. In the larger dataset, we can get some "exotic" peptides with quite large lengths which would throw the whole thing off. I think I should probably fix any parameter that's determined by `average seq legth` to the "expected" average.

**Comment by isthisthat** [comment]
Unfortunately after setting both `-g` and `--use_clinkage`, I get the same issue, i.e. those 30 peptides that cluster when input alone appear as singletons in a larger dataset, using the same cmdline:
`java -Xmx4g -jar Hammock.jar full -i input.txt -f tab -m blosum80.txt --max_shift 9 -g 12 -k 2 --unique -q --use_clinkage`
Is there anything else I can try? I cannot share the data since it's confidential.

**Comment by isthisthat** [comment]
Sorry I had a closer look and the reason seems to be that those sequences are clustering closer to other sequences in the larger datasets. They are definitely not singletons.
