### ISSUE TITLE
beginner question?+installation problems

### ISSUE THREAD

**Issue by dxl3742** [hammock-dev/hammock#13]
Hi, I'm sorry but this is probably a very beginner question, I'm quite new to all this :)
I have followed the guide and installed hmmer, hhsuite and clustal omega in a hammock folder, and I also have the Hammock_v_1.2.0.7z, zip and tar.gz. I'm confused as to what to do next. 
I did this:
cd ~/hammock-1.2.0/examples/MUSI/
java -jar ../../dist/Hammock.jar full -i musi.fa

And got this: unable to access jarfile ../../dist/Hammock.jar
 "Paths are internally defined relative to Hammock.jar file in dist folder". 
I don't know where the dist folder is. 
Any help would be greatly appreciated, thanks in advance!

**Comment by krejciadam** [comment]
Hi! 
The 3 tools are part of the package, so it should run without installing them, although re-compiling on your system might be a good idea. The only thing you really need to install beforehand Java. To run the example, you just need to download the .7z archive from the releases page (https://github.com/krejciadam/hammock/releases), unpack it, and run: 

```
7z x Hammock_v_1.2.0.7z
cd Hammock_v_1.2.0/
java -jar dist/Hammock.jar -i examples/MUSI/musi.fa
```

**Comment by dxl3742** [comment]
thank you so much! I have it working now :) all the best
