### ISSUE TITLE
problem with calculating KLD

### ISSUE THREAD

**Issue by DelphIONe** [hammock-dev/hammock#4]
Hi,

I have one fasta file with ~500000 peptides (length of ~80 AA) and I launch Hammock with full mode.
java -jar ~/softs/Hammock_v_1.2.0/dist/Hammock.jar full -i file.faa

After 8 or 9h of processing, I obtain an java exception like this :

Calculating KLD...
Error. Maybe wrong input file format? Run with --help for a brief description of command line parameters. Trace: 

java.lang.NullPointerException
	at cz.krejciadam.hammock.Statistics.getCorrectedFrequencies(Statistics.java:286)
	at cz.krejciadam.hammock.Statistics.getPeptideKld(Statistics.java:266)
	at cz.krejciadam.hammock.Statistics.getClusterKlds(Statistics.java:224)
	at cz.krejciadam.hammock.Statistics.getClusterKlds(Statistics.java:217)
	at cz.krejciadam.hammock.Statistics.getMeanSystemKld(Statistics.java:181)
	at cz.krejciadam.hammock.Hammock.runClustering(Hammock.java:694)
	at cz.krejciadam.hammock.Hammock.runFull(Hammock.java:379)
	at cz.krejciadam.hammock.Hammock.parseArgs(Hammock.java:271)
	at cz.krejciadam.hammock.Hammock.main(Hammock.java:145)

I have tried also to change the path of the temp directory but it's the same error.

Can you help me please ? The problem can be from my data ?

**Comment by krejciadam** [comment]
Hi!
One possible reason that comes to my mind is that maybe your sequences contain some other characters than the basic 20 AAs. Is that possible by any chance?

**Comment by DelphIONe** [comment]
Thanks for your rapid answer!
I have used biopython to translate (without stop codon), I think it's ok with AA. 
Maybe, some too short peptide ? I didn't filter with a minimal length. I test that!

**Comment by DelphIONe** [comment]
Unfortunately it doesn't work.
If you have any another clue...

**Comment by krejciadam** [comment]
Do you still get the error when you try on a small subset of your dataset? If yes, can you share such smaller dataset?

**Comment by DelphIONe** [comment]
I have 574 333 peptides, it's too much ?
I  try with a downsample ~10 000 peptides.

**Comment by DelphIONe** [comment]
With 10000 peptides, I have the same error :-(
How can I share this smaller dataset with you ?

**Comment by krejciadam** [comment]
The size of the dataset should not be a problem. It is just easier to troubleshoot with a very small dataset that can be processed fast, that is why I asked for a minimal dataset that ends up with an error. So if you can get to even smaller one than 10 K, I'd be glad. If the file is not too large, you can just attach it to your answer here on github.

**Comment by DelphIONe** [comment]
[sub_crep9.txt](https://github.com/krejciadam/hammock/files/7267348/sub_crep9.txt)

Here is!
Thanks for your help

**Comment by krejciadam** [comment]
Thanks. On my end, Hammock successfully finishes with this file - no error. You get the same NullPointerException?

**Comment by DelphIONe** [comment]
Yes, apparently on my side too... The number of reads can be the problem ?

**Comment by krejciadam** [comment]
The input size shoudn't be a problem. I think the problem is with some specific read. Can you try a few subsample files and send the smallest one that produces the error?

**Comment by DelphIONe** [comment]
4000 seems one threshold. I have the error on this file
[sub_crep9.txt](https://github.com/krejciadam/hammock/files/7267505/sub_crep9.txt)

**Comment by krejciadam** [comment]
The problem are indeed invalid amino acid characters. There is this sequence in the dataset:

>M05379:45:000000000-JF9BD:1:2112:9017:25202
ASGNRFVFNTMGWYRQGPGKQRELVATITKSGVTNYGDSVQGRFIISRDIAKNMIDLKMDRLKPEXXXXXXXXXXXXIVHSNYW

X is not a valid amino acid code. Without this sequence, Hammock works fine.

**Comment by DelphIONe** [comment]
:-(
Thanks, ... I'll clean my files.
Thanks again :-)
