### ISSUE TITLE
Length of peptides question

### ISSUE THREAD

**Issue by centaria** [hammock-dev/hammock#7]
Hello,
I was wondering if there is any lower bound on the recommended length of the clustered peptides? For instance, would hammock work on sequences of length 7?
Thank you.

**Comment by krejciadam** [comment]
Hi!
  There is no explicit limit, so Hammock should work with peptides of length 7 and as far as I know, it has been applied to Phage display libraries expressing 7 AA peptides before. You might need to play with the parameters a little, though most of the defaults are calculated based on average input sequence length, so reasonable results could be achieved even with the defaults. I'd still recommend to check out `-h, --min conserved positions` at least, as the default value would be 2 for 7 AA peptides and depending on your application, you might want to increase this.

**Comment by centaria** [comment]
Thank you very much for a quick response, I’ll try this option.
