### ISSUE TITLE
What the length of the aa mer should be compared to putative possible motifs?

### ISSUE THREAD

**Issue by cn6659** [hammock-dev/hammock#8]
I was wondering if we’re looking to uncover motifs of length X what length  Y of the aa mer should be to make sure we can detect it. Could you please suggest any experimental data to back it up?

**Comment by krejciadam** [comment]
I don't think a generic answer to your question can exist. This depends a lot on the diversity of your library and motif conservation. Another important aspect is biological - what is the shortest motif that is meaningful from a functional point of view? In case of e.g. Phage Display experiments, what is the shortest motif that can cause the sequence to bind differently?
