### ISSUE TITLE
replicates in Human SH3 domain in the Hammock paper

### ISSUE THREAD

**Issue by cn6659** [hammock-dev/hammock#9]
Hi,

Using 2457 sequences of 12-aa length from a phage display experiment (human SH3 domain in the paper), I ran Hammock.
command: full -i Src.fa -d Hammock_Src --max_shift 7 -c 65 -t 36

I expected the same number of sequences per cluster, but the numbers are different. Could you please suggest how to reproduce results of the paper?

**Comment by krejciadam** [comment]
Hi!
  Hammock has somewhat evolved over the time, so I'm not surprised the results are different. To get close to results in the publication, I'd recommend running an old version of Hammock (e.g. this : https://github.com/krejciadam/hammock/releases/tag/v1.0.1 importantly, before 1.1) with default parameters. As far as I remember, there was still a little bugfix between the first version published on github and the one used to obtain the results in the publication, so there is a chance the results will still not be exactly identical. But they should surely be very similar for sure.
